apiVersion: vra.vra.provider/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: vra-creds
      namespace: crossplane-system
      key: credentials
